import { Language } from '../types';

export const LANGUAGES: Language[] = [
  { code: 'English', name: 'English', flag: '🇺🇸' },
  { code: 'Japanese', name: 'Japanese', flag: '🇯🇵' },
  { code: 'Korean', name: 'Korean', flag: '🇰🇷' },
  { code: 'Spanish', name: 'Spanish', flag: '🇪🇸' },
  { code: 'Spanish (Argentina)', name: 'Spanish (Argentina)', flag: '🇦🇷' },
  { code: 'Spanish (Bolivia)', name: 'Spanish (Bolivia)', flag: '🇧🇴' },
  { code: 'Spanish (Chile)', name: 'Spanish (Chile)', flag: '🇨🇱' },
  { code: 'Spanish (Colombia)', name: 'Spanish (Colombia)', flag: '🇨🇴' },
  { code: 'Spanish (Costa Rica)', name: 'Spanish (Costa Rica)', flag: '🇨🇷' },
  { code: 'Spanish (Cuba)', name: 'Spanish (Cuba)', flag: '🇨🇺' },
  { code: 'Spanish (Dominican Republic)', name: 'Spanish (Dominican Republic)', flag: '🇩🇴' },
  { code: 'Spanish (Ecuador)', name: 'Spanish (Ecuador)', flag: '🇪🇨' },
  { code: 'Spanish (El Salvador)', name: 'Spanish (El Salvador)', flag: '🇸🇻' },
  { code: 'Spanish (Guatemala)', name: 'Spanish (Guatemala)', flag: '🇬🇹' },
  { code: 'Spanish (Honduras)', name: 'Spanish (Honduras)', flag: '🇭🇳' },
  { code: 'Spanish (Mexico)', name: 'Spanish (Mexico)', flag: '🇲🇽' },
  { code: 'Spanish (Nicaragua)', name: 'Spanish (Nicaragua)', flag: '🇳🇮' },
  { code: 'Spanish (Panama)', name: 'Spanish (Panama)', flag: '🇵🇦' },
  { code: 'Spanish (Paraguay)', name: 'Spanish (Paraguay)', flag: '🇵🇾' },
  { code: 'Spanish (Peru)', name: 'Spanish (Peru)', flag: '🇵🇪' },
  { code: 'Spanish (Puerto Rico)', name: 'Spanish (Puerto Rico)', flag: '🇵🇷' },
  { code: 'Spanish (Uruguay)', name: 'Spanish (Uruguay)', flag: '🇺🇾' },
  { code: 'Spanish (Venezuela)', name: 'Spanish (Venezuela)', flag: '🇻🇪' },
  { code: 'French', name: 'French', flag: '🇫🇷' },
  { code: 'Dutch', name: 'Dutch', flag: '🇳🇱' },
  { code: 'German', name: 'German', flag: '🇩🇪' },
  { code: 'Italian', name: 'Italian', flag: '🇮🇹' },
  { code: 'Portuguese', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'Yoruba', name: 'Yoruba', flag: '🇳🇬' },
  { code: 'Russian', name: 'Russian', flag: '🇷🇺' },
  { code: 'Chinese', name: 'Chinese', flag: '🇨🇳' },
  { code: 'Cantonese', name: 'Cantonese', flag: '🇭🇰' },
  { code: 'Tagalog', name: 'Tagalog', flag: '🇵🇭' },
  { code: 'Arabic', name: 'Arabic', flag: '🇸🇦' },
  { code: 'Hindi', name: 'Hindi', flag: '🇮🇳' },
];